[package]
name = "tetsy-exit-future"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Tetsy Future that signals exit to many receivers"
repository = "https://github.com/tetcoin/tetsy-exit-future"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3.1"
